# Numpy Tutorials

- It creates arrays. This is used for scientific computing. This is super fast

In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [12]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [4,12,3,7,5]
my_lst3 = [1,3,3,3,5]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4, 12,  3,  7,  5],
       [ 1,  3,  3,  3,  5]])

In [14]:
arr.shape

(3, 5)

In [29]:
arr = arr.reshape(5,3)

In [31]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [12,  3,  7],
       [ 5,  1,  3],
       [ 3,  3,  5]])

In [35]:
# Index starts from 0
arr[2,2]

7

In [37]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [38]:
arr = np.arange(0,10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.arange(0,10,2)

In [41]:
arr

array([0, 2, 4, 6, 8])

In [42]:
arr[3:]=100

In [43]:
arr

array([  0,   2,   4, 100, 100])

In [44]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [45]:
arr = np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
arr = np.arange(0,10)
arr[arr<3]

array([0, 1, 2])