# Session_Numpy

In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [4,12,3,7,5]
my_lst3 = [1,3,3,3,5]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr.shape

(3, 5)

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4, 12,  3,  7,  5],
       [ 1,  3,  3,  3,  5]])

### Reshape

In [9]:
new_arr = arr.reshape(5,3)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [12,  3,  7],
       [ 5,  1,  3],
       [ 3,  3,  5]])

In [12]:
new_arr[1,1]

5

In [14]:
new_arr[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [12,  3,  7],
       [ 5,  1,  3],
       [ 3,  3,  5]])

In [17]:
new_arr[1:3,1:3]

array([[5, 4],
       [3, 7]])

### Arange

In [18]:
arr_arange = np.arange(0,10)

In [19]:
arr_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_arange = np.arange(0,10,2)

In [21]:
arr_arange

array([0, 2, 4, 6, 8])

In [22]:
arr_arange[3:] = 0

In [23]:
arr_arange

array([0, 2, 4, 0, 0])

In [26]:
arr = np.arange(0,10).reshape(5,2)

In [27]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Linspace

In [24]:
arr = np.linspace(1,10,50)

In [25]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### hsplit and vsplit

In [30]:
arr = np.arange(0,15).reshape(5,3)

In [37]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [36]:
np.vsplit(arr,5)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]])]

In [38]:
np.hsplit(arr,3)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [40]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.hstack((np.arange(0,6,1).reshape(6,1),np.arange(0,6,1).reshape(6,1),np.arange(0,6,1).reshape(6,1)))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [47]:
np.arange(0,6,1).reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [53]:
np.arange(0,6,1).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
np.vstack((np.arange(0,6,1).reshape(2,3),np.arange(0,6,1).reshape(2,3),np.arange(0,6,1).reshape(2,3)))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])